Adding Support for Metadata
phac-nml/clustersplitter pull request #4
Opened 2024-05-31 19:17 UTC by emarinier

This is a basic first pass of adding support for metadata.

There are other things that need to be updated in the pipeline, but this PR tries to tackle the metadata-related things and only changes other things if there very important (although such related things might need another PR).

## Command

```
rm -rf results; nextflow run main.nf -profile docker --input tests/data/samplesheets/samplesheet.csv --outdir results -params-file assets/parameters.yaml
```

## Input

[samplesheet.csv](https://github.com/phac-nml/clustersplitter/blob/metadata/tests/data/samplesheets/samplesheet.csv): 
```
sample,mlst_alleles,metadata_1,metadata_2,metadata_3,metadata_4,metadata_5,metadata_6,metadata_7,metadata_8
S1,https://raw.githubusercontent.com/phac-nml/clustersplitter/dev/tests/data/profiles/S1.mlst.json,1,"Escherichia coli","EHEC/STEC","Canada","O157:H7",21,"2024/05/30","beef"
S2,https://raw.githubusercontent.com/phac-nml/clustersplitter/dev/tests/data/profiles/S2.mlst.json,1,"Escherichia coli","EHEC/STEC","The United States","O157:H7",55,"2024/05/21","milk"
S3,https://raw.githubusercontent.com/phac-nml/clustersplitter/dev/tests/data/profiles/S3.mlst.json,2,"Escherichia coli","EPEC","France","O125",14,"2024/04/30","cheese"
S4,https://raw.githubusercontent.com/phac-nml/clustersplitter/dev/tests/data/profiles/S4.mlst.json,2,"Escherichia coli","EPEC","France","O125",35,"2024/04/22","cheese"
S5,https://raw.githubusercontent.com/phac-nml/clustersplitter/dev/tests/data/profiles/S5.mlst.json,3,"Escherichia coli","EAEC","Canada","O126:H27",61,"2012/09/01","milk"
S6,https://raw.githubusercontent.com/phac-nml/clustersplitter/dev/tests/data/profiles/S6.mlst.json,unassociated,"Escherichia coli","EAEC","Canada","O111:H21",43,"2011/12/25","fruit"
```

[config.json](https://github.com/phac-nml/clustersplitter/blob/metadata/tests/data/configs/config.json)
```
    {
        "outlier_thresh": "25",
        "clustering_method": "average",
        "clustering_threshold": "500,100,75,50,25,15,10,5,2,1,0",
        "min_cluster_members": 2,
        "partition_column_name": "outbreak",
        "id_column_name": "sample_id",
        "only_report_labeled_columns": "False",
        "skip_qa": "False",
        
        "grouped_metadata_columns":{ 
            "outbreak":{"data_type": "None","label":"National Outbreak Code","default":"","display":"True"},
            "organism":{"data_type": "None","label":"Organism","default":"","display":"True"},
            "subtype":{"data_type": "None","label":"Subtype","default":"","display":"True"},
            "country":{"data_type": "categorical","label":"Country of Collection","default":"","display":"True"},
            "serovar":{"data_type": "categorical","label":"Serovar","default":"","display":"True"},
            "age":{"data_type": "desc_stats","label":"Patient Age (years)","default":"","display":"True"},
            "date":{"data_type": "min_max","label":"Date","default":"","display":"True"},
            "source":{"data_type": "categorical","label":"Source Type","default":"","display":"True"}
        },

        "linelist_columns":{
            "sample":{"data_type": "None","label":"Sample","default":"","display":"True"},
            "outbreak":{"data_type": "None","label":"National Outbreak Code","default":"","display":"True"},
            "organism":{"data_type": "None","label":"Organism","default":"","display":"True"},
            "subtype":{"data_type": "None","label":"Subtype","default":"","display":"True"},
            "country":{"data_type": "categorical","label":"Country of Collection","default":"","display":"True"},
            "serovar":{"data_type": "categorical","label":"Serovar","default":"","display":"True"},
            "age":{"data_type": "desc_stats","label":"Patient Age (years)","default":"","display":"True"},
            "date":{"data_type": "min_max","label":"Date","default":"","display":"True"},
            "source":{"data_type": "categorical","label":"Source Type","default":"","display":"True"}
        }    
    }
```

[parameters.yaml](https://github.com/phac-nml/clustersplitter/blob/metadata/assets/parameters.yaml)
```
partition_column: "outbreak"
metadata_1_header : "outbreak"
metadata_2_header : "organism"
metadata_3_header : "subtype"
metadata_4_header : "country"
metadata_5_header : "serovar"
metadata_6_header : "age"
metadata_7_header : "date"
metadata_8_header : "source"
```

## Output

cluster_summary.tsv
```
National Outbreak Code	Organism	Subtype	Country of Collection	Serovar	Patient Age (years)	Date	Source Type	date_max_value	count_age_43	count_age_21	count_serovar_O125	count_serovar_O157:H7	count_age_55	date_min_value	count_country_The United States	max_dist	count_age_14	count_outliers	count_source_fruit	count_subtype_EAEC	min_dist	age_max_value	count_source_beef	count_serovar_O126:H27	median_dist	count_subtype_EHEC/STEC	age_min_value	count_country_France	age_mean_value	count_serovar_O111:H21	mean_dist	count_organism_Escherichia coli	count_source_milk	count_subtype_EPEC	count_members	count_age_35	count_age_61	age_median_value	count_source_cheese	count_country_Canada
1	Escherichia coli	EHEC/STEC	Canada,The United States	O157:H7	21,55	2024/05/21,2024/05/30	beef,milk	55.0	0	0	0	2	0	21.0	1	3.0	0	0	0	0	3.0	55.0	1	0	3.0	0	21.0	0	38.0	0	3.0	0	1	0	2	0	0	38.0	0	1
2	Escherichia coli	EPEC	France	O125	14,35	2024/04/22,2024/04/30	cheese	35.0	0	0	2	0	0	14.0	0	2.0	0	0	0	0	2.0	35.0	0	0	2.0	0	14.0	2	24.5	0	2.0	0	0	0	2	0	0	24.5	2	0
3	Escherichia coli	EAEC	Canada	O126:H27	61	2012/09/01	milk	61.0	0	0	0	0	0	61.0	0	0	0	0	0	0	0	61.0	0	1	0	0	61.0	0	61.0	0	0	0	1	0	1	0	0	61.0	0	1
unassociated	Escherichia coli	EAEC	Canada	O111:H21	43	2011/12/25	fruit	43.0	0	0	0	0	0	43.0	0	0	0	0	1	0	0	43.0	0	0	0	0	43.0	0	43.0	1	0	0	0	0	1	0	0	43.0	0	1
```

metadata.included.tsv
```
sample	outbreak	organism	subtype	country	serovar	age	date	source
S1	1	Escherichia coli	EHEC/STEC	Canada	O157:H7	21	2024/05/30	beef
S2	1	Escherichia coli	EHEC/STEC	The United States	O157:H7	55	2024/05/21	milk
S3	2	Escherichia coli	EPEC	France	O125	14	2024/04/30	cheese
S4	2	Escherichia coli	EPEC	France	O125	35	2024/04/22	cheese
S5	3	Escherichia coli	EAEC	Canada	O126:H27	61	2012/09/01	milk
S6	unassociated	Escherichia coli	EAEC	Canada	O111:H21	43	2011/12/25	fruit
```

2024-06-03 14:14 UTC, mattheww95 approved these changes
Looks good to me!

2024-06-05 14:29 UTC, kylacochrane approved these changes
Everything looks good Eric 👍

2024-06-06 15:35 UTC, apetkau requested changes
Thanks so much @emarinier . This is great 😄 . Comments below

2024-06-10 18:43 UTC, emarinier commented on tests/data/arborview/expected_1.html
> +        const DATA = "sample\toutbreak\torganism\tsubtype\tcountry\tserovar\tage\tdate\tsource\nS1\t1\tEscherichia coli\tEHEC/STEC\tCanada\tO157:H7\t21\t2024/05/30\tbeef\nS2\t1\tEscherichia coli\tEHE
Updated in 02df5922f21bf09f86b41182d14d934e21bccabb

2024-06-10 18:44 UTC, emarinier commented on workflows/cluster_splitter.nf
> +        partition_col=params.partition_column,
Updated in 916ac01bd321980acefde078ee5c4b7ed8ff04a9

2024-06-12 14:53 UTC, apetkau approved these changes
This looks great to me. Thanks so much @emarinier 😄

2024-06-12 16:31 UTC, merged